### ISSUE TITLE
OLS-2 – where do we work? 

### ISSUE THREAD

**Issue by samuelorion** [osumontreal/meta#10]
Do we work in the osumontreal/OLS-2, or here, in the /meta?

**Comment by dannycolin** [comment]
Whatever you prefer ;).

**Comment by SamGuay** [comment]
I would work in the [meta](https://github.com/osumontreal) so we have everything in here for future reference, but it's up to you in the end. We can also link issue from one repo to another repo to be cited in the other issue like this [here](https://github.com/osumontreal/OLS-2/issues/4).

If we keep the OLS-2 repo, it is a good way to assess how much we've progressed over the OLS-2 program.

**Comment by samuelorion** [comment]
What if we move stuff to the /meta once it's "official". I like the idea that we can keep a track of how we get things done in the /OLS-2.

Je suis ouvert à tout. Alors choisissez. hehe

**Comment by SamGuay** [comment]
Sounds like a good plan!

**Comment by samuelorion** [comment]
@SamGuay What do you use the documentation tag for, in general?
