### ISSUE TITLE
Subdomain for CodiMD

### ISSUE THREAD

**Issue by SamGuay** [osumontreal/meta#5]
Vérifier s'il est possible d'avoir un subdomain permanent tel que https://collab.openscience.ca pour [CodiMD](https://github.com/codimd/server) qui permet realtime collaborative markdown notes on all platforms. 

Si oui :arrow_right: Est-ce qu'on pourra avoir un SSL certificate gratuitement avec herokuapp.. ça reste à confirmer.

Si non :arrow_right: https://collab.openscience.ca redirect vers https://osum-collab.herokuapp.com/

**Comment by SamGuay** [comment]
Quand on se rend à collab.openscience.ca, on retrouve cette page :arrow_down: 
![Weird](https://user-images.githubusercontent.com/30598330/76163838-ae9eb480-6117-11ea-9d3d-950d5a420331.png)

**Comment by dannycolin** [comment]
Ça devrait fonctionner à nouveau.

**Comment by SamGuay** [comment]
On a déménagé vers HackMD  pour le moment. 
Voir https://hackmd.io/@openscience.
